### PR TITLE
move Event.h, FunctionPointer*.h, and mbed-sbrk out of mbed-drivers and into core-utils

### PR DESCRIPTION
**Pull request by rgrover**
This is the first step towards a POSIX platform. These datastructures apply equally well to non-mbed platforms. There will be a corresponding PR against core-utils to accept them.
@bogdanm @bremoran @0xc0170

### CODE REVIEW

**Comment by rgrover** [comment]
I will setup the corresponding PR for core-utils in a moment; please don't merge this PR until both sides of the transition have been cleared and ready for merge.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by rgrover** [comment]
please hold back on the merge to allow me time to move the sbrk family into core-util. @bremoran

**Comment by rgrover** [comment]
The move of mbed-sbrk into core-util is ready for review 
@bogdanm @bremoran @0xc0170

**Comment by 0xc0170** [comment]
LGTM.

I see also there fixes for warnings we had in some tests.

**Comment by rgrover** [comment]
bump

**Comment by 0xc0170** [comment]
@rgrover waiting for minar to be resolved, then we can update dep here , restart jenkins.

**Comment by bogdanm** [comment]
Merged manually.

**Pull request closed without merging**
