### PR TITLE
License - fix apache name and license file

### PR DESCRIPTION
**Pull request by 0xc0170**
@bogdanm @autopulated

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by autopulated** [comment]
the contents of https://github.com/ARMmbed/mbed-drivers/blob/master/apache-2.0.txt looks a bit weird – the copyright statement is old for one thing, also it's double-spaced.

**Comment by 0xc0170** [comment]
We got some versions around. Is this the correct one - https://github.com/ARMmbed/mbed-hal/blob/master/apache-2.0.txt ? I can send new PR correcting this license text

**Comment by autopulated** [comment]
We're meant to have "the full text of http://www.apache.org/licenses/LICENSE-2.0". That mbed-hal link looks closer to me.

**Pull request merged**
