### PR TITLE
Remove mac

### PR DESCRIPTION
**Pull request by sg-**
See https://github.com/ARMmbed/mbed-drivers/issues/125

### CODE REVIEW

**Comment by autopulated** [comment]
IMHO this is the correct fix: be8c90e and 273c437 are included here unintentionally though, I think?

**Comment by sg-** [comment]
err - must have created the branch from a dirty branch :( Will fix that

**Comment by sg-** [comment]
This build passes offline, not sure of the results above

**Comment by 0xc0170** [comment]
Looks good to me. I recall I removed this file, the change was reverted as this function is required by ethernet module. For K64f, it is defined, thus should not cause any failures. Any other target supporting ethernet will need to provide an implementation of this function.

**Comment by 0xc0170** [comment]
@bogdanm @bremoran

**Comment by bogdanm** [comment]
+1

**Comment by sg-** [comment]
merge and publish??

**Comment by devran01** [comment]
@bogdanm CI build was failing because yotta was reporting KeyError: 'not in cache'. New build triggered for this pull request now succeeds in CI system. Can this pull request be merged and a new version of mbed-drivers be published?
@mazimkhan Thank you. :)

**Comment by 0xc0170** [comment]
Yes, will do

**Pull request merged**
