### PR TITLE
Updated dependency on major 1 of greentea-client

### PR DESCRIPTION
**Pull request by bogdanm**

### CODE REVIEW

**Comment by bogdanm** [comment]
Major version 1 of greentea-client might not be published yet, but this change is backwards compatible.
The intention is to release a new *minor* version of this module once this PR is merged.
@0xc0170 @bremoran

**Comment by bremoran** [comment]
-1. This should be a test dependency. Fixing this problem will fix the failures in other modules.

**Comment by bogdanm** [comment]
This one is a regular dependency: https://github.com/ARMmbed/mbed-drivers/blob/master/source/retarget.cpp#L74

**Comment by bremoran** [comment]
https://github.com/ARMmbed/mbed-drivers/blob/master/source/retarget.cpp#L73 ensures that it is only used if the module is present in the build. This is still a test dependency.

**Comment by bogdanm** [comment]
I'm sorry, but I believe it's too risky to make this into a test dependency right now (in the context of the release), because I don't know what could break if we do so. Feel free to open a separate issue for this.

**Comment by bogdanm** [comment]
Merging as it is for now. @bremoran opened #183 to track this.

**Pull request merged**
