### PR TITLE
Adding pinmap function

### PR DESCRIPTION
**Pull request by 0xc0170**
This should fix reported problem of missing definitions for pinmap_function().

References:
- mbed-hal - https://github.com/ARMmbed/mbed-hal/pull/19

Tested with st target which uses pinmap_function() and k64f. A note, the implementation is from mbed - no changes in those 2 functions.

@bogdanm @bremoran

### CODE REVIEW

**Comment by bremoran** [comment]
Looks good, but I would like @bogdanm's input as well.

**Comment by bogdanm** [comment]
Agreed, looks good. The more common code we can factor our, the better. +1.

**Comment by bremoran** [comment]
LGTM

**Comment by 0xc0170** [comment]
For reference,  this should fix https://github.com/ARMmbed/mbed-hal-st-stm32f4/issues/7

**Pull request merged**
