### PR TITLE
Toolchain header file removal

### PR DESCRIPTION
**Pull request by 0xc0170**
We replace it by compiler-polyfill which is a separate module, which
can be reused (referenced).

A note: we should look at weak functions we provide (mac address) and provide an alternative

References:
- compiler-polyfill - https://github.com/ARMmbed/compiler-polyfill/pull/3

@bogdanm @bremoran @bremoran @rgrover

### CODE REVIEW

**Comment by autopulated** [comment]
This section was necessary to build with clang, and hasn't been added to compiler-polyfill:

```c
#if defined(__clang__) && defined(__cplusplus)		
// clang defines main as a c++ symbol if its in a c++ file, gcc always		
// defines main as a c symbol. We expect main to always be a c symbol, so		
// we provide an extern C declaration to force this:		
extern "C" int main();		
#endif // defined(__clang__) && defined(__cplusplus)
```

I think it'd be worth at least opening a PR to add this to compiler-polyfill (seems like the place it belongs), so we don't lose it.

**Comment by 0xc0170** [comment]
@autopulated still needed https://github.com/0xc0170/mbed-drivers/blob/dev_toolchain_removal/source/retarget.cpp#L456 ? If yes, I'll add it to compiler-polyfill

**Comment by autopulated** [comment]
Ahh, probably not. Forgot about that :)

**Comment by bogdanm** [comment]
@0xc0170, why would you add it to compiler-polyfill? I don't think keeping it as it is now raises any issues.

**Pull request merged**
