### PR TITLE
Add doxygen docs to pinmap common

### PR DESCRIPTION
**Pull request by 0xc0170**
Some of the files I looked at this morning

@bogdanm @bremoran @niklas-arm @iriark01

### CODE REVIEW

**Comment by iriark01** [comment]
Is all of mbed-drivers ready for review, or just the files in this PR?

**Comment by 0xc0170** [comment]
@iriark01 only those files, more to come but most probably via separate PR

**Comment by bremoran** [comment]
LGTM

**Comment by iriark01** [comment]
Are all the files finished? I'd rather do them all in one go.

**Comment by bremoran** [comment]
Any objections to merging this?

**Comment by iriark01** [comment]
Not from me, just do let me know when everything is ready for review.

**Pull request closed without merging**
