### PR TITLE
Module - update dependencies cmsis and hal

### PR DESCRIPTION
**Pull request by 0xc0170**
To become this active, there are other few updates of our dependencies to be done

freescale, st, minar platform and core util , anyone to resolve those :fire: ?

@bremoran @bogdanm

### CODE REVIEW

**Comment by bremoran** [comment]
Compiler polyfill is also behind.  It should be 1.1.0

**Comment by 0xc0170** [comment]
Updated the compiler polyfill dep

**Comment by 0xc0170** [comment]
Green :tada:

**Comment by bogdanm** [comment]
Wow, finally green. Great job @0xc0170 ! +1.

**Pull request merged**
