### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by sg-**

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by 0xc0170** [comment]
Part of this is already in #80.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by 0xc0170** [comment]
I can compare what's in here diff and apply it there

**Comment by 0xc0170** [comment]
Please rebase to resolve conflicts.

**Comment by 0xc0170** [comment]
I'll close this as it's quite simple to be send via a new PR. @sg- if not, please reopen

**Pull request closed without merging**
